name: Deploy Docker Beanstalk Workflow
run-name: Deploy Docker Beanstalk Workflow
on:
  workflow_call:
    inputs:
      app_name:
        description: Name of the application to be deployed
        type: string
        required: true
      docker_image:
        description: Image to be deployed with tag
        type: string
        required: true
      container_port: 
        description: Port of the container
        type: number
        required: true

    secrets:
      aws_key_id:
        required: true
      aws_secret_key:
        required: true
      aws_region:
        required: true
      aws_bucket_name:
        required: true

jobs:
  beanstalk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Dockerrun.aws.json file
        run: |
          echo '{"AWSEBDockerrunVersion": "1", "Image": {"Name": "${{ inputs.docker_image }}", "Update": "true"}, "Ports": [{"ContainerPort": ${{ inputs.container_port }}, "HostPort": 80}]}' > Dockerrun.aws.json
          cat Dockerrun.aws.json

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.aws_key_id }}
          aws_secret_key: ${{ secrets.aws_secret_key }}
          region: ${{ secrets.aws_region }}
          application_name: ${{ inputs.app_name }}
          environment_name: ${{ inputs.app_name }}-${{ github.ref_name }}
          version_label: ${{ github.ref_name }}-${{ github.sha }}
          deployment_package: Dockerrun.aws.json
          existing_bucket_name: ${{ secrets.aws_bucket_name }}
          wait_for_deployment: true
